name: 'Generate static redirects'
description: 'Generate static HTML files to handle redirects'
author: 'dilanx'
inputs:
  redirect-configuration:
    description: 'List of redirects'
    required: false
    default: 'redirects.yml'
  destination-directory:
    description: 'Output directory'
    required: false
    default: 'build'
runs:
  using: 'node20'
  main: 'release.js'
branding:
  icon: 'globe'
  color: 'green'
